import 'package:flutter/material.dart';
import 'package:stockskis/stockskis.dart' as stockskis;
import 'package:tarok/constants.dart';
import 'package:tarok/messages.pb.dart' as Messages;

late String playerId;
String name = "Igralec";

List<stockskis.SimpleUser> users = [];
List<List<stockskis.LocalCard>> talon = [];
List<stockskis.LocalCard> cards = [];
List<stockskis.LocalCard> stashedCards = [];
stockskis.LocalCard? firstCard;
List<CardWidget> stih = [];
List<String> cardStih = [];
List<stockskis.SimpleUser> userWidgets = [];
List<stockskis.LocalGame> games = stockskis.GAMES.toList();
List<int> suggestions = [];
Map<int, bool> stihBoolValues = {};

bool lp = false;
bool turn = false;
bool licitiranje = false;
bool licitiram = false;
bool started = false;
bool playing = false;
bool stash = false;
bool showTalon = false;
bool predictions = false;
bool startPredicting = false;
bool kingSelection = false;
bool kingSelect = false;
bool zaruf = false;
bool gameDone = false;
bool requestedGameEnd = false;
bool bots = false;
int playingCount = 0;
int myPosition = 0;
int stashAmount = 0;
int talonSelected = -1;
String selectedKing = "";
String userHasKing = "";
Messages.StartPredictions? myPredictions;
Messages.Predictions? currentPredictions;
Messages.Results? results;
stockskis.LocalCard? premovedCard;
double eval = 0.0;
int sinceLastPrediction = 0;
int countdown = 0;
List<Messages.ChatMessage> chat = [];
bool razpriKarte = false;

bool kontraIgra = false;
bool kontraPagat = false;
bool kontraKralj = false;
bool kontraMondfang = false;
bool trula = false;
bool kralji = false;
bool kraljUltimo = false;
bool pagatUltimo = false;
bool valat = false;
bool barvic = false;
bool mondfang = false;

stockskis.StockSkis? stockskisContext;
late TextEditingController controller;
List prijatelji = [];

void resetVariables() {
  playerId = "";
  name = "Igralec";

  users = [];
  talon = [];
  cards = [];
  stashedCards = [];
  firstCard = null;
  stih = [];
  cardStih = [];
  userWidgets = [];
  games = stockskis.GAMES.toList();
  suggestions = [];
  stihBoolValues = {};

  lp = false;
  turn = false;
  licitiranje = false;
  licitiram = false;
  started = false;
  playing = false;
  stash = false;
  showTalon = false;
  predictions = false;
  startPredicting = false;
  kingSelection = false;
  kingSelect = false;
  zaruf = false;
  gameDone = false;
  requestedGameEnd = false;
  bots = false;
  playingCount = 0;
  myPosition = 0;
  stashAmount = 0;
  talonSelected = -1;
  selectedKing = "";
  userHasKing = "";
  myPredictions = null;
  currentPredictions = null;
  results = null;
  premovedCard = null;
  eval = 0.0;
  sinceLastPrediction = 0;
  countdown = 0;
  chat = [];
  razpriKarte = false;

  kontraIgra = false;
  kontraPagat = false;
  kontraKralj = false;
  kontraMondfang = false;
  trula = false;
  kralji = false;
  kraljUltimo = false;
  pagatUltimo = false;
  valat = false;
  barvic = false;
  mondfang = false;

  prijatelji = [];
  stockskisContext = null;
}
