// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: messages.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Connect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Connect) Reset() {
	*x = Connect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Connect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connect) ProtoMessage() {}

func (x *Connect) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connect.ProtoReflect.Descriptor instead.
func (*Connect) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

type Disconnect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Disconnect) Reset() {
	*x = Disconnect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Disconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disconnect) ProtoMessage() {}

func (x *Disconnect) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disconnect.ProtoReflect.Descriptor instead.
func (*Disconnect) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

type Receive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Receive) Reset() {
	*x = Receive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Receive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receive) ProtoMessage() {}

func (x *Receive) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receive.ProtoReflect.Descriptor instead.
func (*Receive) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

type Send struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Send) Reset() {
	*x = Send{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Send) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Send) ProtoMessage() {}

func (x *Send) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Send.ProtoReflect.Descriptor instead.
func (*Send) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

type ClearDesk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClearDesk) Reset() {
	*x = ClearDesk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearDesk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearDesk) ProtoMessage() {}

func (x *ClearDesk) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearDesk.ProtoReflect.Descriptor instead.
func (*ClearDesk) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

type Connection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rating int32 `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	// Types that are assignable to Type:
	//
	//	*Connection_Join
	//	*Connection_Disconnect
	Type isConnection_Type `protobuf_oneof:"type"`
}

func (x *Connection) Reset() {
	*x = Connection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *Connection) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (m *Connection) GetType() isConnection_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Connection) GetJoin() *Connect {
	if x, ok := x.GetType().(*Connection_Join); ok {
		return x.Join
	}
	return nil
}

func (x *Connection) GetDisconnect() *Disconnect {
	if x, ok := x.GetType().(*Connection_Disconnect); ok {
		return x.Disconnect
	}
	return nil
}

type isConnection_Type interface {
	isConnection_Type()
}

type Connection_Join struct {
	Join *Connect `protobuf:"bytes,3,opt,name=join,proto3,oneof"`
}

type Connection_Disconnect struct {
	Disconnect *Disconnect `protobuf:"bytes,4,opt,name=disconnect,proto3,oneof"`
}

func (*Connection_Join) isConnection_Type() {}

func (*Connection_Disconnect) isConnection_Type() {}

type Licitiranje struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type int32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *Licitiranje) Reset() {
	*x = Licitiranje{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Licitiranje) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Licitiranje) ProtoMessage() {}

func (x *Licitiranje) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Licitiranje.ProtoReflect.Descriptor instead.
func (*Licitiranje) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *Licitiranje) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type LicitiranjeStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LicitiranjeStart) Reset() {
	*x = LicitiranjeStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LicitiranjeStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LicitiranjeStart) ProtoMessage() {}

func (x *LicitiranjeStart) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LicitiranjeStart.ProtoReflect.Descriptor instead.
func (*LicitiranjeStart) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

type Card struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are assignable to Type:
	//
	//	*Card_Receive
	//	*Card_Send
	//	*Card_Request
	Type isCard_Type `protobuf_oneof:"type"`
}

func (x *Card) Reset() {
	*x = Card{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *Card) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (m *Card) GetType() isCard_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Card) GetReceive() *Receive {
	if x, ok := x.GetType().(*Card_Receive); ok {
		return x.Receive
	}
	return nil
}

func (x *Card) GetSend() *Send {
	if x, ok := x.GetType().(*Card_Send); ok {
		return x.Send
	}
	return nil
}

func (x *Card) GetRequest() *Request {
	if x, ok := x.GetType().(*Card_Request); ok {
		return x.Request
	}
	return nil
}

type isCard_Type interface {
	isCard_Type()
}

type Card_Receive struct {
	Receive *Receive `protobuf:"bytes,2,opt,name=receive,proto3,oneof"`
}

type Card_Send struct {
	Send *Send `protobuf:"bytes,3,opt,name=send,proto3,oneof"`
}

type Card_Request struct {
	Request *Request `protobuf:"bytes,4,opt,name=request,proto3,oneof"`
}

func (*Card_Receive) isCard_Type() {}

func (*Card_Send) isCard_Type() {}

func (*Card_Request) isCard_Type() {}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Position int32  `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type ResultsUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User    *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Points  int32 `protobuf:"varint,2,opt,name=points,proto3" json:"points,omitempty"`
	Playing bool  `protobuf:"varint,3,opt,name=playing,proto3" json:"playing,omitempty"`
}

func (x *ResultsUser) Reset() {
	*x = ResultsUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultsUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultsUser) ProtoMessage() {}

func (x *ResultsUser) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultsUser.ProtoReflect.Descriptor instead.
func (*ResultsUser) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{11}
}

func (x *ResultsUser) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ResultsUser) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *ResultsUser) GetPlaying() bool {
	if x != nil {
		return x.Playing
	}
	return false
}

type Results struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User []*ResultsUser `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
}

func (x *Results) Reset() {
	*x = Results{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Results) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Results) ProtoMessage() {}

func (x *Results) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Results.ProtoReflect.Descriptor instead.
func (*Results) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{12}
}

func (x *Results) GetUser() []*ResultsUser {
	if x != nil {
		return x.User
	}
	return nil
}

type GameStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User []*User `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
}

func (x *GameStart) Reset() {
	*x = GameStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStart) ProtoMessage() {}

func (x *GameStart) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStart.ProtoReflect.Descriptor instead.
func (*GameStart) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{13}
}

func (x *GameStart) GetUser() []*User {
	if x != nil {
		return x.User
	}
	return nil
}

type UserList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User []*User `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
}

func (x *UserList) Reset() {
	*x = UserList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserList) ProtoMessage() {}

func (x *UserList) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserList.ProtoReflect.Descriptor instead.
func (*UserList) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{14}
}

func (x *UserList) GetUser() []*User {
	if x != nil {
		return x.User
	}
	return nil
}

type KingSelection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Card string `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	// Types that are assignable to Type:
	//
	//	*KingSelection_Request
	//	*KingSelection_Send
	Type isKingSelection_Type `protobuf_oneof:"type"`
}

func (x *KingSelection) Reset() {
	*x = KingSelection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KingSelection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KingSelection) ProtoMessage() {}

func (x *KingSelection) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KingSelection.ProtoReflect.Descriptor instead.
func (*KingSelection) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{15}
}

func (x *KingSelection) GetCard() string {
	if x != nil {
		return x.Card
	}
	return ""
}

func (m *KingSelection) GetType() isKingSelection_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *KingSelection) GetRequest() *Request {
	if x, ok := x.GetType().(*KingSelection_Request); ok {
		return x.Request
	}
	return nil
}

func (x *KingSelection) GetSend() *Send {
	if x, ok := x.GetType().(*KingSelection_Send); ok {
		return x.Send
	}
	return nil
}

type isKingSelection_Type interface {
	isKingSelection_Type()
}

type KingSelection_Request struct {
	Request *Request `protobuf:"bytes,2,opt,name=request,proto3,oneof"`
}

type KingSelection_Send struct {
	Send *Send `protobuf:"bytes,3,opt,name=send,proto3,oneof"`
}

func (*KingSelection_Request) isKingSelection_Type() {}

func (*KingSelection_Send) isKingSelection_Type() {}

type StartPredictions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentPredictions *Predictions `protobuf:"bytes,1,opt,name=current_predictions,json=currentPredictions,proto3" json:"current_predictions,omitempty"`
}

func (x *StartPredictions) Reset() {
	*x = StartPredictions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartPredictions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPredictions) ProtoMessage() {}

func (x *StartPredictions) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPredictions.ProtoReflect.Descriptor instead.
func (*StartPredictions) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{16}
}

func (x *StartPredictions) GetCurrentPredictions() *Predictions {
	if x != nil {
		return x.CurrentPredictions
	}
	return nil
}

type Predictions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KraljUltimo          *User   `protobuf:"bytes,1,opt,name=kralj_ultimo,json=kraljUltimo,proto3" json:"kralj_ultimo,omitempty"`
	KraljUltimoKontra    int32   `protobuf:"varint,2,opt,name=kralj_ultimo_kontra,json=kraljUltimoKontra,proto3" json:"kralj_ultimo_kontra,omitempty"`
	KraljUltimoKontraDal *User   `protobuf:"bytes,3,opt,name=kralj_ultimo_kontra_dal,json=kraljUltimoKontraDal,proto3" json:"kralj_ultimo_kontra_dal,omitempty"`
	Trula                *User   `protobuf:"bytes,4,opt,name=trula,proto3" json:"trula,omitempty"`
	TrulaKontra          int32   `protobuf:"varint,5,opt,name=trula_kontra,json=trulaKontra,proto3" json:"trula_kontra,omitempty"`
	TrulaKontraDal       *User   `protobuf:"bytes,6,opt,name=trula_kontra_dal,json=trulaKontraDal,proto3" json:"trula_kontra_dal,omitempty"`
	Kralji               *User   `protobuf:"bytes,7,opt,name=kralji,proto3" json:"kralji,omitempty"`
	KraljiKontra         int32   `protobuf:"varint,8,opt,name=kralji_kontra,json=kraljiKontra,proto3" json:"kralji_kontra,omitempty"`
	KraljiKontraDal      *User   `protobuf:"bytes,9,opt,name=kralji_kontra_dal,json=kraljiKontraDal,proto3" json:"kralji_kontra_dal,omitempty"`
	PagatUltimo          *User   `protobuf:"bytes,10,opt,name=pagat_ultimo,json=pagatUltimo,proto3" json:"pagat_ultimo,omitempty"`
	PagatUltimoKontra    int32   `protobuf:"varint,11,opt,name=pagat_ultimo_kontra,json=pagatUltimoKontra,proto3" json:"pagat_ultimo_kontra,omitempty"`
	PagatUltimoKontraDal *User   `protobuf:"bytes,12,opt,name=pagat_ultimo_kontra_dal,json=pagatUltimoKontraDal,proto3" json:"pagat_ultimo_kontra_dal,omitempty"`
	Igra                 []*User `protobuf:"bytes,13,rep,name=igra,proto3" json:"igra,omitempty"`
	IgraKontra           int32   `protobuf:"varint,14,opt,name=igra_kontra,json=igraKontra,proto3" json:"igra_kontra,omitempty"`
	IgraKontraDal        *User   `protobuf:"bytes,15,opt,name=igra_kontra_dal,json=igraKontraDal,proto3" json:"igra_kontra_dal,omitempty"`
	Valat                *User   `protobuf:"bytes,16,opt,name=valat,proto3" json:"valat,omitempty"`
	ValatKontra          int32   `protobuf:"varint,17,opt,name=valat_kontra,json=valatKontra,proto3" json:"valat_kontra,omitempty"`
	ValatKontraDal       *User   `protobuf:"bytes,18,opt,name=valat_kontra_dal,json=valatKontraDal,proto3" json:"valat_kontra_dal,omitempty"`
	BarvniValat          *User   `protobuf:"bytes,19,opt,name=barvni_valat,json=barvniValat,proto3" json:"barvni_valat,omitempty"`
	BarvniValatKontra    int32   `protobuf:"varint,20,opt,name=barvni_valat_kontra,json=barvniValatKontra,proto3" json:"barvni_valat_kontra,omitempty"`
	BarvniValatKontraDal *User   `protobuf:"bytes,21,opt,name=barvni_valat_kontra_dal,json=barvniValatKontraDal,proto3" json:"barvni_valat_kontra_dal,omitempty"`
}

func (x *Predictions) Reset() {
	*x = Predictions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Predictions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Predictions) ProtoMessage() {}

func (x *Predictions) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Predictions.ProtoReflect.Descriptor instead.
func (*Predictions) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{17}
}

func (x *Predictions) GetKraljUltimo() *User {
	if x != nil {
		return x.KraljUltimo
	}
	return nil
}

func (x *Predictions) GetKraljUltimoKontra() int32 {
	if x != nil {
		return x.KraljUltimoKontra
	}
	return 0
}

func (x *Predictions) GetKraljUltimoKontraDal() *User {
	if x != nil {
		return x.KraljUltimoKontraDal
	}
	return nil
}

func (x *Predictions) GetTrula() *User {
	if x != nil {
		return x.Trula
	}
	return nil
}

func (x *Predictions) GetTrulaKontra() int32 {
	if x != nil {
		return x.TrulaKontra
	}
	return 0
}

func (x *Predictions) GetTrulaKontraDal() *User {
	if x != nil {
		return x.TrulaKontraDal
	}
	return nil
}

func (x *Predictions) GetKralji() *User {
	if x != nil {
		return x.Kralji
	}
	return nil
}

func (x *Predictions) GetKraljiKontra() int32 {
	if x != nil {
		return x.KraljiKontra
	}
	return 0
}

func (x *Predictions) GetKraljiKontraDal() *User {
	if x != nil {
		return x.KraljiKontraDal
	}
	return nil
}

func (x *Predictions) GetPagatUltimo() *User {
	if x != nil {
		return x.PagatUltimo
	}
	return nil
}

func (x *Predictions) GetPagatUltimoKontra() int32 {
	if x != nil {
		return x.PagatUltimoKontra
	}
	return 0
}

func (x *Predictions) GetPagatUltimoKontraDal() *User {
	if x != nil {
		return x.PagatUltimoKontraDal
	}
	return nil
}

func (x *Predictions) GetIgra() []*User {
	if x != nil {
		return x.Igra
	}
	return nil
}

func (x *Predictions) GetIgraKontra() int32 {
	if x != nil {
		return x.IgraKontra
	}
	return 0
}

func (x *Predictions) GetIgraKontraDal() *User {
	if x != nil {
		return x.IgraKontraDal
	}
	return nil
}

func (x *Predictions) GetValat() *User {
	if x != nil {
		return x.Valat
	}
	return nil
}

func (x *Predictions) GetValatKontra() int32 {
	if x != nil {
		return x.ValatKontra
	}
	return 0
}

func (x *Predictions) GetValatKontraDal() *User {
	if x != nil {
		return x.ValatKontraDal
	}
	return nil
}

func (x *Predictions) GetBarvniValat() *User {
	if x != nil {
		return x.BarvniValat
	}
	return nil
}

func (x *Predictions) GetBarvniValatKontra() int32 {
	if x != nil {
		return x.BarvniValatKontra
	}
	return 0
}

func (x *Predictions) GetBarvniValatKontraDal() *User {
	if x != nil {
		return x.BarvniValatKontraDal
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{18}
}

type LoginInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *LoginInfo) Reset() {
	*x = LoginInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginInfo) ProtoMessage() {}

func (x *LoginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginInfo.ProtoReflect.Descriptor instead.
func (*LoginInfo) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{19}
}

func (x *LoginInfo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*LoginResponse_Ok
	//	*LoginResponse_Fail_
	Type isLoginResponse_Type `protobuf_oneof:"type"`
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{20}
}

func (m *LoginResponse) GetType() isLoginResponse_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *LoginResponse) GetOk() *LoginResponse_OK {
	if x, ok := x.GetType().(*LoginResponse_Ok); ok {
		return x.Ok
	}
	return nil
}

func (x *LoginResponse) GetFail() *LoginResponse_Fail {
	if x, ok := x.GetType().(*LoginResponse_Fail_); ok {
		return x.Fail
	}
	return nil
}

type isLoginResponse_Type interface {
	isLoginResponse_Type()
}

type LoginResponse_Ok struct {
	Ok *LoginResponse_OK `protobuf:"bytes,1,opt,name=ok,proto3,oneof"`
}

type LoginResponse_Fail_ struct {
	Fail *LoginResponse_Fail `protobuf:"bytes,2,opt,name=fail,proto3,oneof"`
}

func (*LoginResponse_Ok) isLoginResponse_Type() {}

func (*LoginResponse_Fail_) isLoginResponse_Type() {}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	PlayerId string `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameId   string `protobuf:"bytes,3,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	// Types that are assignable to Data:
	//
	//	*Message_Connection
	//	*Message_Licitiranje
	//	*Message_Card
	//	*Message_LicitiranjeStart
	//	*Message_GameStart
	//	*Message_LoginRequest
	//	*Message_LoginInfo
	//	*Message_LoginResponse
	//	*Message_ClearDesk
	//	*Message_Results
	//	*Message_UserList
	//	*Message_KingSelection
	//	*Message_StartPredictions
	//	*Message_Predictions
	Data isMessage_Data `protobuf_oneof:"data"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{21}
}

func (x *Message) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Message) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Message) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (m *Message) GetData() isMessage_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Message) GetConnection() *Connection {
	if x, ok := x.GetData().(*Message_Connection); ok {
		return x.Connection
	}
	return nil
}

func (x *Message) GetLicitiranje() *Licitiranje {
	if x, ok := x.GetData().(*Message_Licitiranje); ok {
		return x.Licitiranje
	}
	return nil
}

func (x *Message) GetCard() *Card {
	if x, ok := x.GetData().(*Message_Card); ok {
		return x.Card
	}
	return nil
}

func (x *Message) GetLicitiranjeStart() *LicitiranjeStart {
	if x, ok := x.GetData().(*Message_LicitiranjeStart); ok {
		return x.LicitiranjeStart
	}
	return nil
}

func (x *Message) GetGameStart() *GameStart {
	if x, ok := x.GetData().(*Message_GameStart); ok {
		return x.GameStart
	}
	return nil
}

func (x *Message) GetLoginRequest() *LoginRequest {
	if x, ok := x.GetData().(*Message_LoginRequest); ok {
		return x.LoginRequest
	}
	return nil
}

func (x *Message) GetLoginInfo() *LoginInfo {
	if x, ok := x.GetData().(*Message_LoginInfo); ok {
		return x.LoginInfo
	}
	return nil
}

func (x *Message) GetLoginResponse() *LoginResponse {
	if x, ok := x.GetData().(*Message_LoginResponse); ok {
		return x.LoginResponse
	}
	return nil
}

func (x *Message) GetClearDesk() *ClearDesk {
	if x, ok := x.GetData().(*Message_ClearDesk); ok {
		return x.ClearDesk
	}
	return nil
}

func (x *Message) GetResults() *Results {
	if x, ok := x.GetData().(*Message_Results); ok {
		return x.Results
	}
	return nil
}

func (x *Message) GetUserList() *UserList {
	if x, ok := x.GetData().(*Message_UserList); ok {
		return x.UserList
	}
	return nil
}

func (x *Message) GetKingSelection() *KingSelection {
	if x, ok := x.GetData().(*Message_KingSelection); ok {
		return x.KingSelection
	}
	return nil
}

func (x *Message) GetStartPredictions() *StartPredictions {
	if x, ok := x.GetData().(*Message_StartPredictions); ok {
		return x.StartPredictions
	}
	return nil
}

func (x *Message) GetPredictions() *Predictions {
	if x, ok := x.GetData().(*Message_Predictions); ok {
		return x.Predictions
	}
	return nil
}

type isMessage_Data interface {
	isMessage_Data()
}

type Message_Connection struct {
	Connection *Connection `protobuf:"bytes,4,opt,name=connection,proto3,oneof"`
}

type Message_Licitiranje struct {
	Licitiranje *Licitiranje `protobuf:"bytes,5,opt,name=licitiranje,proto3,oneof"`
}

type Message_Card struct {
	Card *Card `protobuf:"bytes,6,opt,name=card,proto3,oneof"`
}

type Message_LicitiranjeStart struct {
	LicitiranjeStart *LicitiranjeStart `protobuf:"bytes,7,opt,name=licitiranje_start,json=licitiranjeStart,proto3,oneof"`
}

type Message_GameStart struct {
	GameStart *GameStart `protobuf:"bytes,8,opt,name=game_start,json=gameStart,proto3,oneof"`
}

type Message_LoginRequest struct {
	LoginRequest *LoginRequest `protobuf:"bytes,9,opt,name=login_request,json=loginRequest,proto3,oneof"`
}

type Message_LoginInfo struct {
	LoginInfo *LoginInfo `protobuf:"bytes,10,opt,name=login_info,json=loginInfo,proto3,oneof"`
}

type Message_LoginResponse struct {
	LoginResponse *LoginResponse `protobuf:"bytes,11,opt,name=login_response,json=loginResponse,proto3,oneof"`
}

type Message_ClearDesk struct {
	ClearDesk *ClearDesk `protobuf:"bytes,12,opt,name=clear_desk,json=clearDesk,proto3,oneof"`
}

type Message_Results struct {
	Results *Results `protobuf:"bytes,13,opt,name=results,proto3,oneof"`
}

type Message_UserList struct {
	UserList *UserList `protobuf:"bytes,14,opt,name=user_list,json=userList,proto3,oneof"`
}

type Message_KingSelection struct {
	KingSelection *KingSelection `protobuf:"bytes,15,opt,name=king_selection,json=kingSelection,proto3,oneof"`
}

type Message_StartPredictions struct {
	StartPredictions *StartPredictions `protobuf:"bytes,16,opt,name=start_predictions,json=startPredictions,proto3,oneof"`
}

type Message_Predictions struct {
	Predictions *Predictions `protobuf:"bytes,17,opt,name=predictions,proto3,oneof"`
}

func (*Message_Connection) isMessage_Data() {}

func (*Message_Licitiranje) isMessage_Data() {}

func (*Message_Card) isMessage_Data() {}

func (*Message_LicitiranjeStart) isMessage_Data() {}

func (*Message_GameStart) isMessage_Data() {}

func (*Message_LoginRequest) isMessage_Data() {}

func (*Message_LoginInfo) isMessage_Data() {}

func (*Message_LoginResponse) isMessage_Data() {}

func (*Message_ClearDesk) isMessage_Data() {}

func (*Message_Results) isMessage_Data() {}

func (*Message_UserList) isMessage_Data() {}

func (*Message_KingSelection) isMessage_Data() {}

func (*Message_StartPredictions) isMessage_Data() {}

func (*Message_Predictions) isMessage_Data() {}

type LoginResponse_OK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoginResponse_OK) Reset() {
	*x = LoginResponse_OK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse_OK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse_OK) ProtoMessage() {}

func (x *LoginResponse_OK) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse_OK.ProtoReflect.Descriptor instead.
func (*LoginResponse_OK) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{20, 0}
}

type LoginResponse_Fail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoginResponse_Fail) Reset() {
	*x = LoginResponse_Fail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse_Fail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse_Fail) ProtoMessage() {}

func (x *LoginResponse_Fail) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse_Fail.ProtoReflect.Descriptor instead.
func (*LoginResponse_Fail) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{20, 1}
}

var File_messages_proto protoreflect.FileDescriptor

var file_messages_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x09, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x22, 0x0c, 0x0a, 0x0a, 0x44,
	0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x22, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x22, 0x06, 0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x22, 0x09, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0b, 0x0a, 0x09, 0x43, 0x6c, 0x65, 0x61, 0x72,
	0x44, 0x65, 0x73, 0x6b, 0x22, 0x7b, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1e, 0x0a, 0x04, 0x6a, 0x6f,
	0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x48, 0x00, 0x52, 0x04, 0x6a, 0x6f, 0x69, 0x6e, 0x12, 0x2d, 0x0a, 0x0a, 0x64, 0x69,
	0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x64,
	0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x22, 0x21, 0x0a, 0x0b, 0x4c, 0x69, 0x63, 0x69, 0x74, 0x69, 0x72, 0x61, 0x6e, 0x6a, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x4c, 0x69, 0x63, 0x69, 0x74, 0x69, 0x72, 0x61,
	0x6e, 0x6a, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x22, 0x87, 0x01, 0x0a, 0x04, 0x43, 0x61, 0x72,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x24, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x48, 0x00, 0x52, 0x07,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x12, 0x1b, 0x0a, 0x04, 0x73, 0x65, 0x6e, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x04,
	0x73, 0x65, 0x6e, 0x64, 0x12, 0x24, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x00, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x22, 0x46, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x5a, 0x0a, 0x0b, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x55, 0x73, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70,
	0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x22, 0x2b, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x12, 0x20, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x22, 0x26, 0x0a, 0x09, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x12, 0x19, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x25, 0x0a, 0x08, 0x55,
	0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x22, 0x6e, 0x0a, 0x0d, 0x4b, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x12, 0x24, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x48, 0x00, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x04, 0x73, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x53, 0x65,
	0x6e, 0x64, 0x48, 0x00, 0x52, 0x04, 0x73, 0x65, 0x6e, 0x64, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x22, 0x51, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x72, 0x65, 0x64, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3d, 0x0a, 0x13, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x5f, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x12, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x99, 0x07, 0x0a, 0x0b, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x28, 0x0a, 0x0c, 0x6b, 0x72, 0x61, 0x6c, 0x6a, 0x5f, 0x75,
	0x6c, 0x74, 0x69, 0x6d, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x0b, 0x6b, 0x72, 0x61, 0x6c, 0x6a, 0x55, 0x6c, 0x74, 0x69, 0x6d, 0x6f, 0x12,
	0x2e, 0x0a, 0x13, 0x6b, 0x72, 0x61, 0x6c, 0x6a, 0x5f, 0x75, 0x6c, 0x74, 0x69, 0x6d, 0x6f, 0x5f,
	0x6b, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x6b, 0x72,
	0x61, 0x6c, 0x6a, 0x55, 0x6c, 0x74, 0x69, 0x6d, 0x6f, 0x4b, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x12,
	0x3c, 0x0a, 0x17, 0x6b, 0x72, 0x61, 0x6c, 0x6a, 0x5f, 0x75, 0x6c, 0x74, 0x69, 0x6d, 0x6f, 0x5f,
	0x6b, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x5f, 0x64, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x05, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x14, 0x6b, 0x72, 0x61, 0x6c, 0x6a, 0x55, 0x6c,
	0x74, 0x69, 0x6d, 0x6f, 0x4b, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x44, 0x61, 0x6c, 0x12, 0x1b, 0x0a,
	0x05, 0x74, 0x72, 0x75, 0x6c, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x05, 0x74, 0x72, 0x75, 0x6c, 0x61, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x72,
	0x75, 0x6c, 0x61, 0x5f, 0x6b, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x74, 0x72, 0x75, 0x6c, 0x61, 0x4b, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x12, 0x2f, 0x0a,
	0x10, 0x74, 0x72, 0x75, 0x6c, 0x61, 0x5f, 0x6b, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x5f, 0x64, 0x61,
	0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x0e,
	0x74, 0x72, 0x75, 0x6c, 0x61, 0x4b, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x44, 0x61, 0x6c, 0x12, 0x1d,
	0x0a, 0x06, 0x6b, 0x72, 0x61, 0x6c, 0x6a, 0x69, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x06, 0x6b, 0x72, 0x61, 0x6c, 0x6a, 0x69, 0x12, 0x23, 0x0a,
	0x0d, 0x6b, 0x72, 0x61, 0x6c, 0x6a, 0x69, 0x5f, 0x6b, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6b, 0x72, 0x61, 0x6c, 0x6a, 0x69, 0x4b, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x12, 0x31, 0x0a, 0x11, 0x6b, 0x72, 0x61, 0x6c, 0x6a, 0x69, 0x5f, 0x6b, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x5f, 0x64, 0x61, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x0f, 0x6b, 0x72, 0x61, 0x6c, 0x6a, 0x69, 0x4b, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x44, 0x61, 0x6c, 0x12, 0x28, 0x0a, 0x0c, 0x70, 0x61, 0x67, 0x61, 0x74, 0x5f, 0x75,
	0x6c, 0x74, 0x69, 0x6d, 0x6f, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x0b, 0x70, 0x61, 0x67, 0x61, 0x74, 0x55, 0x6c, 0x74, 0x69, 0x6d, 0x6f, 0x12,
	0x2e, 0x0a, 0x13, 0x70, 0x61, 0x67, 0x61, 0x74, 0x5f, 0x75, 0x6c, 0x74, 0x69, 0x6d, 0x6f, 0x5f,
	0x6b, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x70, 0x61,
	0x67, 0x61, 0x74, 0x55, 0x6c, 0x74, 0x69, 0x6d, 0x6f, 0x4b, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x12,
	0x3c, 0x0a, 0x17, 0x70, 0x61, 0x67, 0x61, 0x74, 0x5f, 0x75, 0x6c, 0x74, 0x69, 0x6d, 0x6f, 0x5f,
	0x6b, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x5f, 0x64, 0x61, 0x6c, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x05, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x14, 0x70, 0x61, 0x67, 0x61, 0x74, 0x55, 0x6c,
	0x74, 0x69, 0x6d, 0x6f, 0x4b, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x44, 0x61, 0x6c, 0x12, 0x19, 0x0a,
	0x04, 0x69, 0x67, 0x72, 0x61, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x04, 0x69, 0x67, 0x72, 0x61, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x67, 0x72, 0x61,
	0x5f, 0x6b, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x69,
	0x67, 0x72, 0x61, 0x4b, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x12, 0x2d, 0x0a, 0x0f, 0x69, 0x67, 0x72,
	0x61, 0x5f, 0x6b, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x5f, 0x64, 0x61, 0x6c, 0x18, 0x0f, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x05, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x0d, 0x69, 0x67, 0x72, 0x61, 0x4b,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x44, 0x61, 0x6c, 0x12, 0x1b, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x61,
	0x74, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x61, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x76, 0x61, 0x6c, 0x61, 0x74, 0x5f, 0x6b,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x18, 0x11, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x76, 0x61, 0x6c,
	0x61, 0x74, 0x4b, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x12, 0x2f, 0x0a, 0x10, 0x76, 0x61, 0x6c, 0x61,
	0x74, 0x5f, 0x6b, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x5f, 0x64, 0x61, 0x6c, 0x18, 0x12, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x05, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x0e, 0x76, 0x61, 0x6c, 0x61, 0x74,
	0x4b, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x44, 0x61, 0x6c, 0x12, 0x28, 0x0a, 0x0c, 0x62, 0x61, 0x72,
	0x76, 0x6e, 0x69, 0x5f, 0x76, 0x61, 0x6c, 0x61, 0x74, 0x18, 0x13, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x05, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x0b, 0x62, 0x61, 0x72, 0x76, 0x6e, 0x69, 0x56, 0x61,
	0x6c, 0x61, 0x74, 0x12, 0x2e, 0x0a, 0x13, 0x62, 0x61, 0x72, 0x76, 0x6e, 0x69, 0x5f, 0x76, 0x61,
	0x6c, 0x61, 0x74, 0x5f, 0x6b, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x18, 0x14, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x11, 0x62, 0x61, 0x72, 0x76, 0x6e, 0x69, 0x56, 0x61, 0x6c, 0x61, 0x74, 0x4b, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x12, 0x3c, 0x0a, 0x17, 0x62, 0x61, 0x72, 0x76, 0x6e, 0x69, 0x5f, 0x76, 0x61,
	0x6c, 0x61, 0x74, 0x5f, 0x6b, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x5f, 0x64, 0x61, 0x6c, 0x18, 0x15,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x14, 0x62, 0x61, 0x72,
	0x76, 0x6e, 0x69, 0x56, 0x61, 0x6c, 0x61, 0x74, 0x4b, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x44, 0x61,
	0x6c, 0x22, 0x0e, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x21, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x75, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x4f, 0x4b, 0x48, 0x00, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x29, 0x0a, 0x04, 0x66, 0x61,
	0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x46, 0x61, 0x69, 0x6c, 0x48, 0x00, 0x52,
	0x04, 0x66, 0x61, 0x69, 0x6c, 0x1a, 0x04, 0x0a, 0x02, 0x4f, 0x4b, 0x1a, 0x06, 0x0a, 0x04, 0x46,
	0x61, 0x69, 0x6c, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x96, 0x06, 0x0a, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x0a, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x0b, 0x6c, 0x69, 0x63, 0x69,
	0x74, 0x69, 0x72, 0x61, 0x6e, 0x6a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x4c, 0x69, 0x63, 0x69, 0x74, 0x69, 0x72, 0x61, 0x6e, 0x6a, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x6c,
	0x69, 0x63, 0x69, 0x74, 0x69, 0x72, 0x61, 0x6e, 0x6a, 0x65, 0x12, 0x1b, 0x0a, 0x04, 0x63, 0x61,
	0x72, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x48,
	0x00, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x12, 0x40, 0x0a, 0x11, 0x6c, 0x69, 0x63, 0x69, 0x74,
	0x69, 0x72, 0x61, 0x6e, 0x6a, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x4c, 0x69, 0x63, 0x69, 0x74, 0x69, 0x72, 0x61, 0x6e, 0x6a, 0x65,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x48, 0x00, 0x52, 0x10, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x69, 0x72,
	0x61, 0x6e, 0x6a, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x2b, 0x0a, 0x0a, 0x67, 0x61, 0x6d,
	0x65, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x48, 0x00, 0x52, 0x09, 0x67, 0x61, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x34, 0x0a, 0x0d, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0c,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x0a,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x09,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x37, 0x0a, 0x0e, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x00, 0x52, 0x0d, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2b, 0x0a, 0x0a, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x5f, 0x64, 0x65, 0x73, 0x6b,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x44, 0x65,
	0x73, 0x6b, 0x48, 0x00, 0x52, 0x09, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x44, 0x65, 0x73, 0x6b, 0x12,
	0x24, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x48, 0x00, 0x52, 0x07, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x28, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x37, 0x0a, 0x0e, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4b, 0x69, 0x6e, 0x67, 0x53, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0d, 0x6b, 0x69, 0x6e, 0x67, 0x53,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x40, 0x0a, 0x11, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x5f, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x10, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x72, 0x65, 0x64, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x48, 0x00, 0x52, 0x10, 0x73, 0x74, 0x61, 0x72, 0x74, 0x50,
	0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x30, 0x0a, 0x0b, 0x70, 0x72,
	0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x48, 0x00, 0x52,
	0x0b, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x06, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x42, 0x1d, 0x5a, 0x1b, 0x2e, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData = file_messages_proto_rawDesc
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_proto_rawDescData)
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_messages_proto_goTypes = []interface{}{
	(*Connect)(nil),            // 0: Connect
	(*Disconnect)(nil),         // 1: Disconnect
	(*Receive)(nil),            // 2: Receive
	(*Send)(nil),               // 3: Send
	(*Request)(nil),            // 4: Request
	(*ClearDesk)(nil),          // 5: ClearDesk
	(*Connection)(nil),         // 6: Connection
	(*Licitiranje)(nil),        // 7: Licitiranje
	(*LicitiranjeStart)(nil),   // 8: LicitiranjeStart
	(*Card)(nil),               // 9: Card
	(*User)(nil),               // 10: User
	(*ResultsUser)(nil),        // 11: ResultsUser
	(*Results)(nil),            // 12: Results
	(*GameStart)(nil),          // 13: GameStart
	(*UserList)(nil),           // 14: UserList
	(*KingSelection)(nil),      // 15: KingSelection
	(*StartPredictions)(nil),   // 16: StartPredictions
	(*Predictions)(nil),        // 17: Predictions
	(*LoginRequest)(nil),       // 18: LoginRequest
	(*LoginInfo)(nil),          // 19: LoginInfo
	(*LoginResponse)(nil),      // 20: LoginResponse
	(*Message)(nil),            // 21: Message
	(*LoginResponse_OK)(nil),   // 22: LoginResponse.OK
	(*LoginResponse_Fail)(nil), // 23: LoginResponse.Fail
}
var file_messages_proto_depIdxs = []int32{
	0,  // 0: Connection.join:type_name -> Connect
	1,  // 1: Connection.disconnect:type_name -> Disconnect
	2,  // 2: Card.receive:type_name -> Receive
	3,  // 3: Card.send:type_name -> Send
	4,  // 4: Card.request:type_name -> Request
	10, // 5: ResultsUser.user:type_name -> User
	11, // 6: Results.user:type_name -> ResultsUser
	10, // 7: GameStart.user:type_name -> User
	10, // 8: UserList.user:type_name -> User
	4,  // 9: KingSelection.request:type_name -> Request
	3,  // 10: KingSelection.send:type_name -> Send
	17, // 11: StartPredictions.current_predictions:type_name -> Predictions
	10, // 12: Predictions.kralj_ultimo:type_name -> User
	10, // 13: Predictions.kralj_ultimo_kontra_dal:type_name -> User
	10, // 14: Predictions.trula:type_name -> User
	10, // 15: Predictions.trula_kontra_dal:type_name -> User
	10, // 16: Predictions.kralji:type_name -> User
	10, // 17: Predictions.kralji_kontra_dal:type_name -> User
	10, // 18: Predictions.pagat_ultimo:type_name -> User
	10, // 19: Predictions.pagat_ultimo_kontra_dal:type_name -> User
	10, // 20: Predictions.igra:type_name -> User
	10, // 21: Predictions.igra_kontra_dal:type_name -> User
	10, // 22: Predictions.valat:type_name -> User
	10, // 23: Predictions.valat_kontra_dal:type_name -> User
	10, // 24: Predictions.barvni_valat:type_name -> User
	10, // 25: Predictions.barvni_valat_kontra_dal:type_name -> User
	22, // 26: LoginResponse.ok:type_name -> LoginResponse.OK
	23, // 27: LoginResponse.fail:type_name -> LoginResponse.Fail
	6,  // 28: Message.connection:type_name -> Connection
	7,  // 29: Message.licitiranje:type_name -> Licitiranje
	9,  // 30: Message.card:type_name -> Card
	8,  // 31: Message.licitiranje_start:type_name -> LicitiranjeStart
	13, // 32: Message.game_start:type_name -> GameStart
	18, // 33: Message.login_request:type_name -> LoginRequest
	19, // 34: Message.login_info:type_name -> LoginInfo
	20, // 35: Message.login_response:type_name -> LoginResponse
	5,  // 36: Message.clear_desk:type_name -> ClearDesk
	12, // 37: Message.results:type_name -> Results
	14, // 38: Message.user_list:type_name -> UserList
	15, // 39: Message.king_selection:type_name -> KingSelection
	16, // 40: Message.start_predictions:type_name -> StartPredictions
	17, // 41: Message.predictions:type_name -> Predictions
	42, // [42:42] is the sub-list for method output_type
	42, // [42:42] is the sub-list for method input_type
	42, // [42:42] is the sub-list for extension type_name
	42, // [42:42] is the sub-list for extension extendee
	0,  // [0:42] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Connect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Disconnect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Receive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Send); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearDesk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Connection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Licitiranje); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LicitiranjeStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Card); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultsUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Results); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KingSelection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartPredictions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Predictions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse_OK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse_Fail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_messages_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*Connection_Join)(nil),
		(*Connection_Disconnect)(nil),
	}
	file_messages_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*Card_Receive)(nil),
		(*Card_Send)(nil),
		(*Card_Request)(nil),
	}
	file_messages_proto_msgTypes[15].OneofWrappers = []interface{}{
		(*KingSelection_Request)(nil),
		(*KingSelection_Send)(nil),
	}
	file_messages_proto_msgTypes[20].OneofWrappers = []interface{}{
		(*LoginResponse_Ok)(nil),
		(*LoginResponse_Fail_)(nil),
	}
	file_messages_proto_msgTypes[21].OneofWrappers = []interface{}{
		(*Message_Connection)(nil),
		(*Message_Licitiranje)(nil),
		(*Message_Card)(nil),
		(*Message_LicitiranjeStart)(nil),
		(*Message_GameStart)(nil),
		(*Message_LoginRequest)(nil),
		(*Message_LoginInfo)(nil),
		(*Message_LoginResponse)(nil),
		(*Message_ClearDesk)(nil),
		(*Message_Results)(nil),
		(*Message_UserList)(nil),
		(*Message_KingSelection)(nil),
		(*Message_StartPredictions)(nil),
		(*Message_Predictions)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_rawDesc = nil
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
