// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.19.6
// source: lobby_messages.proto

package lobby_messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_lobby_messages_proto_rawDescGZIP(), []int{0}
}

type LoginInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *LoginInfo) Reset() {
	*x = LoginInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginInfo) ProtoMessage() {}

func (x *LoginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginInfo.ProtoReflect.Descriptor instead.
func (*LoginInfo) Descriptor() ([]byte, []int) {
	return file_lobby_messages_proto_rawDescGZIP(), []int{1}
}

func (x *LoginInfo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*LoginResponse_Ok
	//	*LoginResponse_Fail_
	Type isLoginResponse_Type `protobuf_oneof:"type"`
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_lobby_messages_proto_rawDescGZIP(), []int{2}
}

func (m *LoginResponse) GetType() isLoginResponse_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *LoginResponse) GetOk() *LoginResponse_OK {
	if x, ok := x.GetType().(*LoginResponse_Ok); ok {
		return x.Ok
	}
	return nil
}

func (x *LoginResponse) GetFail() *LoginResponse_Fail {
	if x, ok := x.GetType().(*LoginResponse_Fail_); ok {
		return x.Fail
	}
	return nil
}

type isLoginResponse_Type interface {
	isLoginResponse_Type()
}

type LoginResponse_Ok struct {
	Ok *LoginResponse_OK `protobuf:"bytes,1,opt,name=ok,proto3,oneof"`
}

type LoginResponse_Fail_ struct {
	Fail *LoginResponse_Fail `protobuf:"bytes,2,opt,name=fail,proto3,oneof"`
}

func (*LoginResponse_Ok) isLoginResponse_Type() {}

func (*LoginResponse_Fail_) isLoginResponse_Type() {}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rating int32  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_lobby_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type GameCreated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId            string    `protobuf:"bytes,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Players           []*Player `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	MondfangRadelci   bool      `protobuf:"varint,5,opt,name=mondfang_radelci,json=mondfangRadelci,proto3" json:"mondfang_radelci,omitempty"`
	Skisfang          bool      `protobuf:"varint,6,opt,name=skisfang,proto3" json:"skisfang,omitempty"`
	NapovedanMondfang bool      `protobuf:"varint,7,opt,name=napovedan_mondfang,json=napovedanMondfang,proto3" json:"napovedan_mondfang,omitempty"`
	KontraKazen       bool      `protobuf:"varint,8,opt,name=kontra_kazen,json=kontraKazen,proto3" json:"kontra_kazen,omitempty"`
	TotalTime         int32     `protobuf:"varint,15,opt,name=total_time,json=totalTime,proto3" json:"total_time,omitempty"`
	AdditionalTime    float32   `protobuf:"fixed32,16,opt,name=additional_time,json=additionalTime,proto3" json:"additional_time,omitempty"`
	Type              string    `protobuf:"bytes,17,opt,name=type,proto3" json:"type,omitempty"`
	RequiredPlayers   int32     `protobuf:"varint,18,opt,name=requiredPlayers,proto3" json:"requiredPlayers,omitempty"`
	Started           bool      `protobuf:"varint,19,opt,name=started,proto3" json:"started,omitempty"`
	Private           bool      `protobuf:"varint,20,opt,name=private,proto3" json:"private,omitempty"`
	Priority          bool      `protobuf:"varint,21,opt,name=priority,proto3" json:"priority,omitempty"`
}

func (x *GameCreated) Reset() {
	*x = GameCreated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCreated) ProtoMessage() {}

func (x *GameCreated) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCreated.ProtoReflect.Descriptor instead.
func (*GameCreated) Descriptor() ([]byte, []int) {
	return file_lobby_messages_proto_rawDescGZIP(), []int{4}
}

func (x *GameCreated) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameCreated) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameCreated) GetMondfangRadelci() bool {
	if x != nil {
		return x.MondfangRadelci
	}
	return false
}

func (x *GameCreated) GetSkisfang() bool {
	if x != nil {
		return x.Skisfang
	}
	return false
}

func (x *GameCreated) GetNapovedanMondfang() bool {
	if x != nil {
		return x.NapovedanMondfang
	}
	return false
}

func (x *GameCreated) GetKontraKazen() bool {
	if x != nil {
		return x.KontraKazen
	}
	return false
}

func (x *GameCreated) GetTotalTime() int32 {
	if x != nil {
		return x.TotalTime
	}
	return 0
}

func (x *GameCreated) GetAdditionalTime() float32 {
	if x != nil {
		return x.AdditionalTime
	}
	return 0
}

func (x *GameCreated) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GameCreated) GetRequiredPlayers() int32 {
	if x != nil {
		return x.RequiredPlayers
	}
	return 0
}

func (x *GameCreated) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *GameCreated) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

func (x *GameCreated) GetPriority() bool {
	if x != nil {
		return x.Priority
	}
	return false
}

type GameDisbanded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId string `protobuf:"bytes,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
}

func (x *GameDisbanded) Reset() {
	*x = GameDisbanded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameDisbanded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameDisbanded) ProtoMessage() {}

func (x *GameDisbanded) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameDisbanded.ProtoReflect.Descriptor instead.
func (*GameDisbanded) Descriptor() ([]byte, []int) {
	return file_lobby_messages_proto_rawDescGZIP(), []int{5}
}

func (x *GameDisbanded) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type GameJoin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId string  `protobuf:"bytes,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Player *Player `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *GameJoin) Reset() {
	*x = GameJoin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameJoin) ProtoMessage() {}

func (x *GameJoin) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameJoin.ProtoReflect.Descriptor instead.
func (*GameJoin) Descriptor() ([]byte, []int) {
	return file_lobby_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GameJoin) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameJoin) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

type GameLeave struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId string  `protobuf:"bytes,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Player *Player `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *GameLeave) Reset() {
	*x = GameLeave{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameLeave) ProtoMessage() {}

func (x *GameLeave) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameLeave.ProtoReflect.Descriptor instead.
func (*GameLeave) Descriptor() ([]byte, []int) {
	return file_lobby_messages_proto_rawDescGZIP(), []int{7}
}

func (x *GameLeave) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameLeave) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

type GameInvite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId string `protobuf:"bytes,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
}

func (x *GameInvite) Reset() {
	*x = GameInvite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInvite) ProtoMessage() {}

func (x *GameInvite) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInvite.ProtoReflect.Descriptor instead.
func (*GameInvite) Descriptor() ([]byte, []int) {
	return file_lobby_messages_proto_rawDescGZIP(), []int{8}
}

func (x *GameInvite) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type GameMove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId   string `protobuf:"bytes,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Priority bool   `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
}

func (x *GameMove) Reset() {
	*x = GameMove{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMove) ProtoMessage() {}

func (x *GameMove) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMove.ProtoReflect.Descriptor instead.
func (*GameMove) Descriptor() ([]byte, []int) {
	return file_lobby_messages_proto_rawDescGZIP(), []int{9}
}

func (x *GameMove) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameMove) GetPriority() bool {
	if x != nil {
		return x.Priority
	}
	return false
}

// 0 - offline
// 1 - online
// 2 - in-game
type FriendOnlineStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *FriendOnlineStatus) Reset() {
	*x = FriendOnlineStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendOnlineStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendOnlineStatus) ProtoMessage() {}

func (x *FriendOnlineStatus) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendOnlineStatus.ProtoReflect.Descriptor instead.
func (*FriendOnlineStatus) Descriptor() ([]byte, []int) {
	return file_lobby_messages_proto_rawDescGZIP(), []int{10}
}

func (x *FriendOnlineStatus) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type Friend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email  string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Id     string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are assignable to Data:
	//
	//	*Friend_Connected_
	//	*Friend_Outgoing_
	//	*Friend_Incoming_
	Data isFriend_Data `protobuf_oneof:"data"`
}

func (x *Friend) Reset() {
	*x = Friend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_messages_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Friend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Friend) ProtoMessage() {}

func (x *Friend) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_messages_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Friend.ProtoReflect.Descriptor instead.
func (*Friend) Descriptor() ([]byte, []int) {
	return file_lobby_messages_proto_rawDescGZIP(), []int{11}
}

func (x *Friend) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Friend) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Friend) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Friend) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (m *Friend) GetData() isFriend_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Friend) GetConnected() *Friend_Connected {
	if x, ok := x.GetData().(*Friend_Connected_); ok {
		return x.Connected
	}
	return nil
}

func (x *Friend) GetOutgoing() *Friend_Outgoing {
	if x, ok := x.GetData().(*Friend_Outgoing_); ok {
		return x.Outgoing
	}
	return nil
}

func (x *Friend) GetIncoming() *Friend_Incoming {
	if x, ok := x.GetData().(*Friend_Incoming_); ok {
		return x.Incoming
	}
	return nil
}

type isFriend_Data interface {
	isFriend_Data()
}

type Friend_Connected_ struct {
	Connected *Friend_Connected `protobuf:"bytes,5,opt,name=connected,proto3,oneof"`
}

type Friend_Outgoing_ struct {
	Outgoing *Friend_Outgoing `protobuf:"bytes,6,opt,name=outgoing,proto3,oneof"`
}

type Friend_Incoming_ struct {
	Incoming *Friend_Incoming `protobuf:"bytes,7,opt,name=incoming,proto3,oneof"`
}

func (*Friend_Connected_) isFriend_Data() {}

func (*Friend_Outgoing_) isFriend_Data() {}

func (*Friend_Incoming_) isFriend_Data() {}

type FriendRequestAcceptDecline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RelationshipId string `protobuf:"bytes,1,opt,name=relationshipId,proto3" json:"relationshipId,omitempty"`
	Accept         bool   `protobuf:"varint,2,opt,name=accept,proto3" json:"accept,omitempty"`
}

func (x *FriendRequestAcceptDecline) Reset() {
	*x = FriendRequestAcceptDecline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_messages_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendRequestAcceptDecline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestAcceptDecline) ProtoMessage() {}

func (x *FriendRequestAcceptDecline) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_messages_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestAcceptDecline.ProtoReflect.Descriptor instead.
func (*FriendRequestAcceptDecline) Descriptor() ([]byte, []int) {
	return file_lobby_messages_proto_rawDescGZIP(), []int{12}
}

func (x *FriendRequestAcceptDecline) GetRelationshipId() string {
	if x != nil {
		return x.RelationshipId
	}
	return ""
}

func (x *FriendRequestAcceptDecline) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

type FriendRequestSend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *FriendRequestSend) Reset() {
	*x = FriendRequestSend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_messages_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendRequestSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestSend) ProtoMessage() {}

func (x *FriendRequestSend) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_messages_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestSend.ProtoReflect.Descriptor instead.
func (*FriendRequestSend) Descriptor() ([]byte, []int) {
	return file_lobby_messages_proto_rawDescGZIP(), []int{13}
}

func (x *FriendRequestSend) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RemoveFriend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RelationshipId string `protobuf:"bytes,1,opt,name=relationshipId,proto3" json:"relationshipId,omitempty"`
}

func (x *RemoveFriend) Reset() {
	*x = RemoveFriend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_messages_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFriend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriend) ProtoMessage() {}

func (x *RemoveFriend) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_messages_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriend.ProtoReflect.Descriptor instead.
func (*RemoveFriend) Descriptor() ([]byte, []int) {
	return file_lobby_messages_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveFriend) GetRelationshipId() string {
	if x != nil {
		return x.RelationshipId
	}
	return ""
}

type Replay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url       string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	GameId    string `protobuf:"bytes,2,opt,name=gameId,proto3" json:"gameId,omitempty"`
	CreatedAt string `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (x *Replay) Reset() {
	*x = Replay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_messages_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Replay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Replay) ProtoMessage() {}

func (x *Replay) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_messages_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Replay.ProtoReflect.Descriptor instead.
func (*Replay) Descriptor() ([]byte, []int) {
	return file_lobby_messages_proto_rawDescGZIP(), []int{15}
}

func (x *Replay) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Replay) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *Replay) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type LobbyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	// Types that are assignable to Data:
	//
	//	*LobbyMessage_LoginRequest
	//	*LobbyMessage_LoginInfo
	//	*LobbyMessage_LoginResponse
	//	*LobbyMessage_GameCreated
	//	*LobbyMessage_GameDisbanded
	//	*LobbyMessage_GameJoin
	//	*LobbyMessage_GameLeave
	//	*LobbyMessage_GameMove
	//	*LobbyMessage_GameInvite
	//	*LobbyMessage_FriendOnlineStatus
	//	*LobbyMessage_Friend
	//	*LobbyMessage_FriendRequestAcceptDecline
	//	*LobbyMessage_FriendRequestSend
	//	*LobbyMessage_RemoveFriend
	//	*LobbyMessage_Replay
	Data isLobbyMessage_Data `protobuf_oneof:"data"`
}

func (x *LobbyMessage) Reset() {
	*x = LobbyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_messages_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LobbyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyMessage) ProtoMessage() {}

func (x *LobbyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_messages_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyMessage.ProtoReflect.Descriptor instead.
func (*LobbyMessage) Descriptor() ([]byte, []int) {
	return file_lobby_messages_proto_rawDescGZIP(), []int{16}
}

func (x *LobbyMessage) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (m *LobbyMessage) GetData() isLobbyMessage_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *LobbyMessage) GetLoginRequest() *LoginRequest {
	if x, ok := x.GetData().(*LobbyMessage_LoginRequest); ok {
		return x.LoginRequest
	}
	return nil
}

func (x *LobbyMessage) GetLoginInfo() *LoginInfo {
	if x, ok := x.GetData().(*LobbyMessage_LoginInfo); ok {
		return x.LoginInfo
	}
	return nil
}

func (x *LobbyMessage) GetLoginResponse() *LoginResponse {
	if x, ok := x.GetData().(*LobbyMessage_LoginResponse); ok {
		return x.LoginResponse
	}
	return nil
}

func (x *LobbyMessage) GetGameCreated() *GameCreated {
	if x, ok := x.GetData().(*LobbyMessage_GameCreated); ok {
		return x.GameCreated
	}
	return nil
}

func (x *LobbyMessage) GetGameDisbanded() *GameDisbanded {
	if x, ok := x.GetData().(*LobbyMessage_GameDisbanded); ok {
		return x.GameDisbanded
	}
	return nil
}

func (x *LobbyMessage) GetGameJoin() *GameJoin {
	if x, ok := x.GetData().(*LobbyMessage_GameJoin); ok {
		return x.GameJoin
	}
	return nil
}

func (x *LobbyMessage) GetGameLeave() *GameLeave {
	if x, ok := x.GetData().(*LobbyMessage_GameLeave); ok {
		return x.GameLeave
	}
	return nil
}

func (x *LobbyMessage) GetGameMove() *GameMove {
	if x, ok := x.GetData().(*LobbyMessage_GameMove); ok {
		return x.GameMove
	}
	return nil
}

func (x *LobbyMessage) GetGameInvite() *GameInvite {
	if x, ok := x.GetData().(*LobbyMessage_GameInvite); ok {
		return x.GameInvite
	}
	return nil
}

func (x *LobbyMessage) GetFriendOnlineStatus() *FriendOnlineStatus {
	if x, ok := x.GetData().(*LobbyMessage_FriendOnlineStatus); ok {
		return x.FriendOnlineStatus
	}
	return nil
}

func (x *LobbyMessage) GetFriend() *Friend {
	if x, ok := x.GetData().(*LobbyMessage_Friend); ok {
		return x.Friend
	}
	return nil
}

func (x *LobbyMessage) GetFriendRequestAcceptDecline() *FriendRequestAcceptDecline {
	if x, ok := x.GetData().(*LobbyMessage_FriendRequestAcceptDecline); ok {
		return x.FriendRequestAcceptDecline
	}
	return nil
}

func (x *LobbyMessage) GetFriendRequestSend() *FriendRequestSend {
	if x, ok := x.GetData().(*LobbyMessage_FriendRequestSend); ok {
		return x.FriendRequestSend
	}
	return nil
}

func (x *LobbyMessage) GetRemoveFriend() *RemoveFriend {
	if x, ok := x.GetData().(*LobbyMessage_RemoveFriend); ok {
		return x.RemoveFriend
	}
	return nil
}

func (x *LobbyMessage) GetReplay() *Replay {
	if x, ok := x.GetData().(*LobbyMessage_Replay); ok {
		return x.Replay
	}
	return nil
}

type isLobbyMessage_Data interface {
	isLobbyMessage_Data()
}

type LobbyMessage_LoginRequest struct {
	LoginRequest *LoginRequest `protobuf:"bytes,10,opt,name=login_request,json=loginRequest,proto3,oneof"`
}

type LobbyMessage_LoginInfo struct {
	LoginInfo *LoginInfo `protobuf:"bytes,11,opt,name=login_info,json=loginInfo,proto3,oneof"`
}

type LobbyMessage_LoginResponse struct {
	LoginResponse *LoginResponse `protobuf:"bytes,12,opt,name=login_response,json=loginResponse,proto3,oneof"`
}

type LobbyMessage_GameCreated struct {
	GameCreated *GameCreated `protobuf:"bytes,13,opt,name=game_created,json=gameCreated,proto3,oneof"`
}

type LobbyMessage_GameDisbanded struct {
	GameDisbanded *GameDisbanded `protobuf:"bytes,14,opt,name=game_disbanded,json=gameDisbanded,proto3,oneof"`
}

type LobbyMessage_GameJoin struct {
	GameJoin *GameJoin `protobuf:"bytes,15,opt,name=game_join,json=gameJoin,proto3,oneof"`
}

type LobbyMessage_GameLeave struct {
	GameLeave *GameLeave `protobuf:"bytes,16,opt,name=game_leave,json=gameLeave,proto3,oneof"`
}

type LobbyMessage_GameMove struct {
	GameMove *GameMove `protobuf:"bytes,17,opt,name=game_move,json=gameMove,proto3,oneof"`
}

type LobbyMessage_GameInvite struct {
	GameInvite *GameInvite `protobuf:"bytes,18,opt,name=game_invite,json=gameInvite,proto3,oneof"`
}

type LobbyMessage_FriendOnlineStatus struct {
	FriendOnlineStatus *FriendOnlineStatus `protobuf:"bytes,20,opt,name=friend_online_status,json=friendOnlineStatus,proto3,oneof"`
}

type LobbyMessage_Friend struct {
	Friend *Friend `protobuf:"bytes,21,opt,name=friend,proto3,oneof"`
}

type LobbyMessage_FriendRequestAcceptDecline struct {
	FriendRequestAcceptDecline *FriendRequestAcceptDecline `protobuf:"bytes,22,opt,name=friend_request_accept_decline,json=friendRequestAcceptDecline,proto3,oneof"`
}

type LobbyMessage_FriendRequestSend struct {
	FriendRequestSend *FriendRequestSend `protobuf:"bytes,23,opt,name=friend_request_send,json=friendRequestSend,proto3,oneof"`
}

type LobbyMessage_RemoveFriend struct {
	RemoveFriend *RemoveFriend `protobuf:"bytes,24,opt,name=remove_friend,json=removeFriend,proto3,oneof"`
}

type LobbyMessage_Replay struct {
	Replay *Replay `protobuf:"bytes,25,opt,name=replay,proto3,oneof"`
}

func (*LobbyMessage_LoginRequest) isLobbyMessage_Data() {}

func (*LobbyMessage_LoginInfo) isLobbyMessage_Data() {}

func (*LobbyMessage_LoginResponse) isLobbyMessage_Data() {}

func (*LobbyMessage_GameCreated) isLobbyMessage_Data() {}

func (*LobbyMessage_GameDisbanded) isLobbyMessage_Data() {}

func (*LobbyMessage_GameJoin) isLobbyMessage_Data() {}

func (*LobbyMessage_GameLeave) isLobbyMessage_Data() {}

func (*LobbyMessage_GameMove) isLobbyMessage_Data() {}

func (*LobbyMessage_GameInvite) isLobbyMessage_Data() {}

func (*LobbyMessage_FriendOnlineStatus) isLobbyMessage_Data() {}

func (*LobbyMessage_Friend) isLobbyMessage_Data() {}

func (*LobbyMessage_FriendRequestAcceptDecline) isLobbyMessage_Data() {}

func (*LobbyMessage_FriendRequestSend) isLobbyMessage_Data() {}

func (*LobbyMessage_RemoveFriend) isLobbyMessage_Data() {}

func (*LobbyMessage_Replay) isLobbyMessage_Data() {}

type LoginResponse_OK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoginResponse_OK) Reset() {
	*x = LoginResponse_OK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_messages_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse_OK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse_OK) ProtoMessage() {}

func (x *LoginResponse_OK) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_messages_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse_OK.ProtoReflect.Descriptor instead.
func (*LoginResponse_OK) Descriptor() ([]byte, []int) {
	return file_lobby_messages_proto_rawDescGZIP(), []int{2, 0}
}

type LoginResponse_Fail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoginResponse_Fail) Reset() {
	*x = LoginResponse_Fail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_messages_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse_Fail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse_Fail) ProtoMessage() {}

func (x *LoginResponse_Fail) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_messages_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse_Fail.ProtoReflect.Descriptor instead.
func (*LoginResponse_Fail) Descriptor() ([]byte, []int) {
	return file_lobby_messages_proto_rawDescGZIP(), []int{2, 1}
}

type Friend_Incoming struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Friend_Incoming) Reset() {
	*x = Friend_Incoming{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_messages_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Friend_Incoming) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Friend_Incoming) ProtoMessage() {}

func (x *Friend_Incoming) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_messages_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Friend_Incoming.ProtoReflect.Descriptor instead.
func (*Friend_Incoming) Descriptor() ([]byte, []int) {
	return file_lobby_messages_proto_rawDescGZIP(), []int{11, 0}
}

type Friend_Outgoing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Friend_Outgoing) Reset() {
	*x = Friend_Outgoing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_messages_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Friend_Outgoing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Friend_Outgoing) ProtoMessage() {}

func (x *Friend_Outgoing) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_messages_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Friend_Outgoing.ProtoReflect.Descriptor instead.
func (*Friend_Outgoing) Descriptor() ([]byte, []int) {
	return file_lobby_messages_proto_rawDescGZIP(), []int{11, 1}
}

type Friend_Connected struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Friend_Connected) Reset() {
	*x = Friend_Connected{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_messages_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Friend_Connected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Friend_Connected) ProtoMessage() {}

func (x *Friend_Connected) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_messages_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Friend_Connected.ProtoReflect.Descriptor instead.
func (*Friend_Connected) Descriptor() ([]byte, []int) {
	return file_lobby_messages_proto_rawDescGZIP(), []int{11, 2}
}

var File_lobby_messages_proto protoreflect.FileDescriptor

var file_lobby_messages_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x0e, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x21, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x93, 0x01, 0x0a, 0x0d, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x02, 0x6f,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4f, 0x4b, 0x48, 0x00, 0x52, 0x02, 0x6f, 0x6b, 0x12,
	0x38, 0x0a, 0x04, 0x66, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x46, 0x61, 0x69,
	0x6c, 0x48, 0x00, 0x52, 0x04, 0x66, 0x61, 0x69, 0x6c, 0x1a, 0x04, 0x0a, 0x02, 0x4f, 0x4b, 0x1a,
	0x06, 0x0a, 0x04, 0x46, 0x61, 0x69, 0x6c, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22,
	0x44, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x22, 0xc6, 0x03, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x30, 0x0a,
	0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12,
	0x29, 0x0a, 0x10, 0x6d, 0x6f, 0x6e, 0x64, 0x66, 0x61, 0x6e, 0x67, 0x5f, 0x72, 0x61, 0x64, 0x65,
	0x6c, 0x63, 0x69, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x6d, 0x6f, 0x6e, 0x64, 0x66,
	0x61, 0x6e, 0x67, 0x52, 0x61, 0x64, 0x65, 0x6c, 0x63, 0x69, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6b,
	0x69, 0x73, 0x66, 0x61, 0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x73, 0x6b,
	0x69, 0x73, 0x66, 0x61, 0x6e, 0x67, 0x12, 0x2d, 0x0a, 0x12, 0x6e, 0x61, 0x70, 0x6f, 0x76, 0x65,
	0x64, 0x61, 0x6e, 0x5f, 0x6d, 0x6f, 0x6e, 0x64, 0x66, 0x61, 0x6e, 0x67, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x11, 0x6e, 0x61, 0x70, 0x6f, 0x76, 0x65, 0x64, 0x61, 0x6e, 0x4d, 0x6f, 0x6e,
	0x64, 0x66, 0x61, 0x6e, 0x67, 0x12, 0x21, 0x0a, 0x0c, 0x6b, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x5f,
	0x6b, 0x61, 0x7a, 0x65, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x6b, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x4b, 0x61, 0x7a, 0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x61, 0x64, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x0e, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x12, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x72,
	0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x13, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x15,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x22, 0x27,
	0x0a, 0x0d, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x69, 0x73, 0x62, 0x61, 0x6e, 0x64, 0x65, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x52, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x4a,
	0x6f, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x06, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6c, 0x6f,
	0x62, 0x62, 0x79, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x53, 0x0a, 0x09, 0x47,
	0x61, 0x6d, 0x65, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64,
	0x12, 0x2e, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x22, 0x24, 0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x3e, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x6f,
	0x76, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72,
	0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x70, 0x72,
	0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x22, 0x2c, 0x0a, 0x12, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0xc7, 0x02, 0x0a, 0x06, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x40, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x12, 0x3d, 0x0a, 0x08, 0x6f, 0x75, 0x74, 0x67, 0x6f, 0x69, 0x6e, 0x67, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x4f, 0x75,
	0x74, 0x67, 0x6f, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x08, 0x6f, 0x75, 0x74, 0x67, 0x6f, 0x69,
	0x6e, 0x67, 0x12, 0x3d, 0x0a, 0x08, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x49, 0x6e, 0x63,
	0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x08, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e,
	0x67, 0x1a, 0x0a, 0x0a, 0x08, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x1a, 0x0a, 0x0a,
	0x08, 0x4f, 0x75, 0x74, 0x67, 0x6f, 0x69, 0x6e, 0x67, 0x1a, 0x0b, 0x0a, 0x09, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x5c,
	0x0a, 0x1a, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41,
	0x63, 0x63, 0x65, 0x70, 0x74, 0x44, 0x65, 0x63, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x26, 0x0a, 0x0e,
	0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68,
	0x69, 0x70, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x22, 0x29, 0x0a, 0x11,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x65, 0x6e,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x36, 0x0a, 0x0c, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x72, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x49, 0x64, 0x22,
	0x50, 0x0a, 0x06, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x67,
	0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d,
	0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x22, 0xba, 0x08, 0x0a, 0x0c, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x43, 0x0a, 0x0d, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0c, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x46, 0x0a, 0x0e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0c, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x47, 0x61, 0x6d, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0b, 0x67,
	0x61, 0x6d, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x46, 0x0a, 0x0e, 0x67, 0x61,
	0x6d, 0x65, 0x5f, 0x64, 0x69, 0x73, 0x62, 0x61, 0x6e, 0x64, 0x65, 0x64, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x69, 0x73, 0x62, 0x61, 0x6e, 0x64, 0x65,
	0x64, 0x48, 0x00, 0x52, 0x0d, 0x67, 0x61, 0x6d, 0x65, 0x44, 0x69, 0x73, 0x62, 0x61, 0x6e, 0x64,
	0x65, 0x64, 0x12, 0x37, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6a, 0x6f, 0x69, 0x6e, 0x18,
	0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x48,
	0x00, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x3a, 0x0a, 0x0a, 0x67,
	0x61, 0x6d, 0x65, 0x5f, 0x6c, 0x65, 0x61, 0x76, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x48, 0x00, 0x52, 0x09, 0x67, 0x61,
	0x6d, 0x65, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x12, 0x37, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f,
	0x6d, 0x6f, 0x76, 0x65, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x6f, 0x62,
	0x62, 0x79, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x47, 0x61, 0x6d, 0x65,
	0x4d, 0x6f, 0x76, 0x65, 0x48, 0x00, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4d, 0x6f, 0x76, 0x65,
	0x12, 0x3d, 0x0a, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x18,
	0x12, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x48, 0x00, 0x52, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x12,
	0x56, 0x0a, 0x14, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x48, 0x00, 0x52, 0x12, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x30, 0x0a, 0x06, 0x66, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x18, 0x15, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x48,
	0x00, 0x52, 0x06, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x12, 0x6f, 0x0a, 0x1d, 0x66, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x65,
	0x70, 0x74, 0x5f, 0x64, 0x65, 0x63, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x16, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2a, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41,
	0x63, 0x63, 0x65, 0x70, 0x74, 0x44, 0x65, 0x63, 0x6c, 0x69, 0x6e, 0x65, 0x48, 0x00, 0x52, 0x1a,
	0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x63, 0x63,
	0x65, 0x70, 0x74, 0x44, 0x65, 0x63, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x53, 0x0a, 0x13, 0x66, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x6e,
	0x64, 0x18, 0x17, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x65, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x11, 0x66, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x65, 0x6e, 0x64, 0x12,
	0x43, 0x0a, 0x0d, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x18, 0x18, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x0c, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x12, 0x30, 0x0a, 0x06, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x18, 0x19,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x48, 0x00, 0x52, 0x06,
	0x72, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x23,
	0x5a, 0x21, 0x2e, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lobby_messages_proto_rawDescOnce sync.Once
	file_lobby_messages_proto_rawDescData = file_lobby_messages_proto_rawDesc
)

func file_lobby_messages_proto_rawDescGZIP() []byte {
	file_lobby_messages_proto_rawDescOnce.Do(func() {
		file_lobby_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_lobby_messages_proto_rawDescData)
	})
	return file_lobby_messages_proto_rawDescData
}

var file_lobby_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_lobby_messages_proto_goTypes = []interface{}{
	(*LoginRequest)(nil),               // 0: lobby_messages.LoginRequest
	(*LoginInfo)(nil),                  // 1: lobby_messages.LoginInfo
	(*LoginResponse)(nil),              // 2: lobby_messages.LoginResponse
	(*Player)(nil),                     // 3: lobby_messages.Player
	(*GameCreated)(nil),                // 4: lobby_messages.GameCreated
	(*GameDisbanded)(nil),              // 5: lobby_messages.GameDisbanded
	(*GameJoin)(nil),                   // 6: lobby_messages.GameJoin
	(*GameLeave)(nil),                  // 7: lobby_messages.GameLeave
	(*GameInvite)(nil),                 // 8: lobby_messages.GameInvite
	(*GameMove)(nil),                   // 9: lobby_messages.GameMove
	(*FriendOnlineStatus)(nil),         // 10: lobby_messages.FriendOnlineStatus
	(*Friend)(nil),                     // 11: lobby_messages.Friend
	(*FriendRequestAcceptDecline)(nil), // 12: lobby_messages.FriendRequestAcceptDecline
	(*FriendRequestSend)(nil),          // 13: lobby_messages.FriendRequestSend
	(*RemoveFriend)(nil),               // 14: lobby_messages.RemoveFriend
	(*Replay)(nil),                     // 15: lobby_messages.Replay
	(*LobbyMessage)(nil),               // 16: lobby_messages.LobbyMessage
	(*LoginResponse_OK)(nil),           // 17: lobby_messages.LoginResponse.OK
	(*LoginResponse_Fail)(nil),         // 18: lobby_messages.LoginResponse.Fail
	(*Friend_Incoming)(nil),            // 19: lobby_messages.Friend.Incoming
	(*Friend_Outgoing)(nil),            // 20: lobby_messages.Friend.Outgoing
	(*Friend_Connected)(nil),           // 21: lobby_messages.Friend.Connected
}
var file_lobby_messages_proto_depIdxs = []int32{
	17, // 0: lobby_messages.LoginResponse.ok:type_name -> lobby_messages.LoginResponse.OK
	18, // 1: lobby_messages.LoginResponse.fail:type_name -> lobby_messages.LoginResponse.Fail
	3,  // 2: lobby_messages.GameCreated.players:type_name -> lobby_messages.Player
	3,  // 3: lobby_messages.GameJoin.player:type_name -> lobby_messages.Player
	3,  // 4: lobby_messages.GameLeave.player:type_name -> lobby_messages.Player
	21, // 5: lobby_messages.Friend.connected:type_name -> lobby_messages.Friend.Connected
	20, // 6: lobby_messages.Friend.outgoing:type_name -> lobby_messages.Friend.Outgoing
	19, // 7: lobby_messages.Friend.incoming:type_name -> lobby_messages.Friend.Incoming
	0,  // 8: lobby_messages.LobbyMessage.login_request:type_name -> lobby_messages.LoginRequest
	1,  // 9: lobby_messages.LobbyMessage.login_info:type_name -> lobby_messages.LoginInfo
	2,  // 10: lobby_messages.LobbyMessage.login_response:type_name -> lobby_messages.LoginResponse
	4,  // 11: lobby_messages.LobbyMessage.game_created:type_name -> lobby_messages.GameCreated
	5,  // 12: lobby_messages.LobbyMessage.game_disbanded:type_name -> lobby_messages.GameDisbanded
	6,  // 13: lobby_messages.LobbyMessage.game_join:type_name -> lobby_messages.GameJoin
	7,  // 14: lobby_messages.LobbyMessage.game_leave:type_name -> lobby_messages.GameLeave
	9,  // 15: lobby_messages.LobbyMessage.game_move:type_name -> lobby_messages.GameMove
	8,  // 16: lobby_messages.LobbyMessage.game_invite:type_name -> lobby_messages.GameInvite
	10, // 17: lobby_messages.LobbyMessage.friend_online_status:type_name -> lobby_messages.FriendOnlineStatus
	11, // 18: lobby_messages.LobbyMessage.friend:type_name -> lobby_messages.Friend
	12, // 19: lobby_messages.LobbyMessage.friend_request_accept_decline:type_name -> lobby_messages.FriendRequestAcceptDecline
	13, // 20: lobby_messages.LobbyMessage.friend_request_send:type_name -> lobby_messages.FriendRequestSend
	14, // 21: lobby_messages.LobbyMessage.remove_friend:type_name -> lobby_messages.RemoveFriend
	15, // 22: lobby_messages.LobbyMessage.replay:type_name -> lobby_messages.Replay
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_lobby_messages_proto_init() }
func file_lobby_messages_proto_init() {
	if File_lobby_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lobby_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameCreated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameDisbanded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameJoin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameLeave); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameInvite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameMove); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendOnlineStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_messages_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Friend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_messages_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendRequestAcceptDecline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_messages_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendRequestSend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_messages_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveFriend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_messages_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Replay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_messages_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LobbyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_messages_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse_OK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_messages_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse_Fail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_messages_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Friend_Incoming); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_messages_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Friend_Outgoing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_messages_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Friend_Connected); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_lobby_messages_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*LoginResponse_Ok)(nil),
		(*LoginResponse_Fail_)(nil),
	}
	file_lobby_messages_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*Friend_Connected_)(nil),
		(*Friend_Outgoing_)(nil),
		(*Friend_Incoming_)(nil),
	}
	file_lobby_messages_proto_msgTypes[16].OneofWrappers = []interface{}{
		(*LobbyMessage_LoginRequest)(nil),
		(*LobbyMessage_LoginInfo)(nil),
		(*LobbyMessage_LoginResponse)(nil),
		(*LobbyMessage_GameCreated)(nil),
		(*LobbyMessage_GameDisbanded)(nil),
		(*LobbyMessage_GameJoin)(nil),
		(*LobbyMessage_GameLeave)(nil),
		(*LobbyMessage_GameMove)(nil),
		(*LobbyMessage_GameInvite)(nil),
		(*LobbyMessage_FriendOnlineStatus)(nil),
		(*LobbyMessage_Friend)(nil),
		(*LobbyMessage_FriendRequestAcceptDecline)(nil),
		(*LobbyMessage_FriendRequestSend)(nil),
		(*LobbyMessage_RemoveFriend)(nil),
		(*LobbyMessage_Replay)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lobby_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lobby_messages_proto_goTypes,
		DependencyIndexes: file_lobby_messages_proto_depIdxs,
		MessageInfos:      file_lobby_messages_proto_msgTypes,
	}.Build()
	File_lobby_messages_proto = out.File
	file_lobby_messages_proto_rawDesc = nil
	file_lobby_messages_proto_goTypes = nil
	file_lobby_messages_proto_depIdxs = nil
}
