import 'package:stockskis/src/types.dart';

final List<LocalCard> CARDS = [
  LocalCard(asset: "/kara/1", worth: 1, worthOver: 4, alt: "1 kara"),
  LocalCard(asset: "/kara/2", worth: 1, worthOver: 3, alt: "2 kara"),
  LocalCard(asset: "/kara/3", worth: 1, worthOver: 2, alt: "3 kara"),
  LocalCard(asset: "/kara/4", worth: 1, worthOver: 1, alt: "4 kara"),
  LocalCard(asset: "/kara/pob", worth: 2, worthOver: 5, alt: "Kara pob"),
  LocalCard(asset: "/kara/kaval", worth: 3, worthOver: 6, alt: "Kara kaval"),
  LocalCard(asset: "/kara/dama", worth: 4, worthOver: 7, alt: "Kara dama"),
  LocalCard(asset: "/kara/kralj", worth: 5, worthOver: 8, alt: "Kara kralj"),
  LocalCard(asset: "/kriz/7", worth: 1, worthOver: 1, alt: "7 križ"),
  LocalCard(asset: "/kriz/8", worth: 1, worthOver: 2, alt: "8 križ"),
  LocalCard(asset: "/kriz/9", worth: 1, worthOver: 3, alt: "9 križ"),
  LocalCard(asset: "/kriz/10", worth: 1, worthOver: 4, alt: "10 križ"),
  LocalCard(asset: "/kriz/pob", worth: 2, worthOver: 5, alt: "Križ pob"),
  LocalCard(asset: "/kriz/kaval", worth: 3, worthOver: 6, alt: "Križ kaval"),
  LocalCard(asset: "/kriz/dama", worth: 4, worthOver: 7, alt: "Križ dama"),
  LocalCard(asset: "/kriz/kralj", worth: 5, worthOver: 8, alt: "Križ kralj"),
  LocalCard(asset: "/pik/7", worth: 1, worthOver: 1, alt: "7 pik"),
  LocalCard(asset: "/pik/8", worth: 1, worthOver: 2, alt: "8 pik"),
  LocalCard(asset: "/pik/9", worth: 1, worthOver: 3, alt: "9 pik"),
  LocalCard(asset: "/pik/10", worth: 1, worthOver: 4, alt: "10 pik"),
  LocalCard(asset: "/pik/pob", worth: 2, worthOver: 5, alt: "Pik pob"),
  LocalCard(asset: "/pik/kaval", worth: 3, worthOver: 6, alt: "Pik kaval"),
  LocalCard(asset: "/pik/dama", worth: 4, worthOver: 7, alt: "Pik dama"),
  LocalCard(asset: "/pik/kralj", worth: 5, worthOver: 8, alt: "Pik kralj"),
  LocalCard(asset: "/src/1", worth: 1, worthOver: 4, alt: "1 src"),
  LocalCard(asset: "/src/2", worth: 1, worthOver: 3, alt: "2 src"),
  LocalCard(asset: "/src/3", worth: 1, worthOver: 2, alt: "3 src"),
  LocalCard(asset: "/src/4", worth: 1, worthOver: 1, alt: "4 src"),
  LocalCard(asset: "/src/pob", worth: 2, worthOver: 5, alt: "Src pob"),
  LocalCard(asset: "/src/kaval", worth: 3, worthOver: 6, alt: "Src kaval"),
  LocalCard(asset: "/src/dama", worth: 4, worthOver: 7, alt: "Src dama"),
  LocalCard(asset: "/src/kralj", worth: 5, worthOver: 8, alt: "Src kralj"),
  LocalCard(asset: "/taroki/pagat", worth: 5, worthOver: 11, alt: "Pagat"),
  LocalCard(asset: "/taroki/2", worth: 1, worthOver: 12, alt: "2"),
  LocalCard(asset: "/taroki/3", worth: 1, worthOver: 13, alt: "3"),
  LocalCard(asset: "/taroki/4", worth: 1, worthOver: 14, alt: "4"),
  LocalCard(asset: "/taroki/5", worth: 1, worthOver: 15, alt: "5"),
  LocalCard(asset: "/taroki/6", worth: 1, worthOver: 16, alt: "6"),
  LocalCard(asset: "/taroki/7", worth: 1, worthOver: 17, alt: "7"),
  LocalCard(asset: "/taroki/8", worth: 1, worthOver: 18, alt: "8"),
  LocalCard(asset: "/taroki/9", worth: 1, worthOver: 19, alt: "9"),
  LocalCard(asset: "/taroki/10", worth: 1, worthOver: 20, alt: "10"),
  LocalCard(asset: "/taroki/11", worth: 1, worthOver: 21, alt: "11"),
  LocalCard(asset: "/taroki/12", worth: 1, worthOver: 22, alt: "12"),
  LocalCard(asset: "/taroki/13", worth: 1, worthOver: 23, alt: "13"),
  LocalCard(asset: "/taroki/14", worth: 1, worthOver: 24, alt: "14"),
  LocalCard(asset: "/taroki/15", worth: 1, worthOver: 25, alt: "15"),
  LocalCard(asset: "/taroki/16", worth: 1, worthOver: 26, alt: "16"),
  LocalCard(asset: "/taroki/17", worth: 1, worthOver: 27, alt: "17"),
  LocalCard(asset: "/taroki/18", worth: 1, worthOver: 28, alt: "18"),
  LocalCard(asset: "/taroki/19", worth: 1, worthOver: 29, alt: "19"),
  LocalCard(asset: "/taroki/20", worth: 1, worthOver: 30, alt: "20"),
  LocalCard(asset: "/taroki/mond", worth: 5, worthOver: 31, alt: "Mond"),
  LocalCard(asset: "/taroki/skis", worth: 5, worthOver: 32, alt: "Škis"),
];
