bool PRIREDI_IGRO = false;
bool GARANTIRAN_ZARUF = false;
bool AUTOSTART_GAME = true;
bool ODPRTE_IGRE = false;
bool BARVIC = false;
bool DEBUG_LOGGING = true;
bool BERAC = false;
String HEKE_DOBI = "player";
const List<int> GAMEMODE_CONFIGURATION = [];
